Repository Segelzwerg/FamilyFotoAndroid, pull requests merged in 2020-10, with the labels that each got.

#17 testing/instrumental-jacoco-report
  app/build.gradle
  app/src/androidTest/java/com/segelzwerg/familyfotoandroid/ContextTest.java
Labels: hacktoberfest-accepted, test

#18 ci/connected-checks
  .github/workflows/android.yml
Labels: hacktoberfest-accepted, test

#9 feature/login-server
  app/build.gradle
  app/config/pmd/pmd.xml
  app/src/androidTest/java/com/segelzwerg/familyfotoandroid/ui/TestLoginActivity.java
  app/src/androidTest/java/com/segelzwerg/familyfotoandroid/ui/elements/TestLoginButton.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/segelzwerg/familyfotoandroid/FamilyFotoAndroidApplication.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/accounts/FamilyFotoAuthenticator.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/accounts/FamilyFotoService.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/accounts/package-info.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/familyfotoservice/AuthToken.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/familyfotoservice/BaseUrlModule.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/familyfotoservice/FamilyFotoServerService.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/familyfotoservice/LoginCredentials.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/familyfotoservice/UserManager.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/familyfotoservice/package-info.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/familyfotoservice/utils/RetrofitClientUtil.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/familyfotoservice/utils/package-info.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/ui/LoginActivity.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/ui/LoginActivityModule.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/ui/LoginCallBack.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/ui/MainActivity.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/ui/PasswordWatcher.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/ui/RequiredFieldWatcher.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/ui/UsernameWatcher.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/ui/elements/LoginButton.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/ui/elements/RequiredField.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/ui/elements/package-info.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/authenticator.xml
  app/src/test/java/com/segelzwerg/familyfotoandroid/ExampleUnitTest.java
  app/src/test/java/com/segelzwerg/familyfotoandroid/TestFamilyFotoServerService.java
  app/src/test/java/com/segelzwerg/familyfotoandroid/familyfotoservice/BaseUrlModuleTest.java
  app/src/test/java/com/segelzwerg/familyfotoandroid/familyfotoservice/LoginCredentialsTest.java
  app/src/test/java/com/segelzwerg/familyfotoandroid/familyfotoservice/UserManagerTest.java
  app/src/test/java/com/segelzwerg/familyfotoandroid/ui/LoginCallBackTest.java
  app/src/test/java/com/segelzwerg/familyfotoandroid/ui/TestPasswordWatcher.java
  app/src/test/java/com/segelzwerg/familyfotoandroid/ui/TestUsernameWatcher.java
  build.gradle
Labels: hacktoberfest-accepted

#20 Adding gitignore for a Java Project
  .gitignore
Labels: hacktoberfest-accepted

#29 feature/save-auth-token
  app/build.gradle
  app/src/androidTest/java/com/segelzwerg/familyfotoandroid/ui/TestLoginActivity.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/familyfotoservice/ManagerExtractionException.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/familyfotoservice/UserManager.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/ui/LoginActivity.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/ui/LoginCallBack.java
  app/src/main/java/com/segelzwerg/familyfotoandroid/ui/MainActivity.java
  app/src/test/java/com/segelzwerg/familyfotoandroid/familyfotoservice/TestUserManager.java
  app/src/test/java/com/segelzwerg/familyfotoandroid/familyfotoservice/UserManagerTest.java
  app/src/test/java/com/segelzwerg/familyfotoandroid/ui/LoginCallBackTest.java
Labels: enhancement
